apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "telemetry.fullname" . }}-postgresql
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "telemetry.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  serviceName: {{ include "telemetry.fullname" . }}-postgresql-hl
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "telemetry.name" . }}
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "telemetry.name" . }}
        app.kubernetes.io/component: database
    spec:
      containers:
        - name: postgresql
          image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
          imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}
          ports:
            - name: postgresql
              containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.auth.database | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.auth.username | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.auth.existingSecret }}
                  key: {{ .Values.postgresql.auth.secretKeys.passwordKey }}
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          resources:
            {{- toYaml .Values.postgresql.resources | nindent 12 }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{ .Values.global.storageClass }}
        resources:
          requests:
            storage: {{ .Values.postgresql.persistence.size }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "telemetry.fullname" . }}-postgresql
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "telemetry.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgresql
      name: postgresql
  selector:
    app.kubernetes.io/name: {{ include "telemetry.name" . }}
    app.kubernetes.io/component: database
